site_name: BBG-Wiki

theme:
  name: material
  palette:
    primary: orange
    accent: orange
  logo: assets/images/bbglabLOGO_small.png
  favicon: assets/images/bbglabLOGO_small.png
  features:
    - navigation.top
    - content.code.annotate

markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
