site_name: BBG-Wiki

repo_url: https://github.com/bbglab/bbgwiki
repo_name: bbgwiki
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: orange
    accent: orange
  logo: assets/images/bbglabLOGO_small.png
  favicon: assets/images/bbglabLOGO_small.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.top
    - content.code.annotate
    - search.suggest
    - content.action.edit
    - content.action.view


plugins: 
  - search
  - tags
  - git-committers:
      repository: bbglab/bbgwiki
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: material.emoji.to_svg
  - stylesheets/extra.css
