name: markdownlint

on:
  pull_request:

jobs:
  markdownlint:
    name: Lint Markdown Files
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          fix: true
          config: '.markdownlint.json'
          globs: 'docs/**/*.md'
        continue-on-error: false

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: markdownlint[bot]
          commit_user_email: markdownlint@bot.dev
